### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#866]
We are heading towards Splatoon 3 launch and there are a lot of features to work on. This issue tracks larger features and lists how they are different from the Splatoon 2 sendou.ink. It is representing near future plans for sendou.ink. Everything is subject to change at any time.

- [ ] https://github.com/Sendouc/sendou.ink/issues/860
- [x] https://github.com/Sendouc/sendou.ink/issues/830
- [x] Build analyzer for Splatoon 3
  
- [ ] https://github.com/Sendouc/sendou.ink/issues/848 (automatically gone when replay is stale)
- [ ] https://github.com/Sendouc/sendou.ink/issues/867
- [ ] Splatoon 2 X rank badges. Upload all of Splatoon 2 data (league, x rank, splatfests) or just badges?

- [ ] Builds
  - [x] Can have many weapons (up to 5) per build
  - [ ] Ability selector better UX. Can drag. Hold shift to duplicate abilities.
  
- [ ] Maplist
  - [ ] Save maplist (giving name and code)
  - [ ] Generate maplist for scrims using a Lohi 
  - [ ] You can generate maps from 2 map lists. (E.g. your team has one tournament they practice for and the opponent has another. Maplist generated accommodates both.)
  - [x] Link map lists to a calendar event (shows on the calendar page)
  - [x] Create map list while creating calendar event
- [ ] Top 500 browser with Splatoon 3 stats
  - [ ] EU+NA / JP separated.
  - [ ] Combine Top 500 and Top 500 tier lists pages. Show more stats from top 500 data.
  
- [ ] User search page.
  - [ ] Combine free agents to this. Set free agent post on user profile. On user search page can filter for free agents.

- [ ] Map planner
  - [ ] Rewrite using maybe something like https://excalidraw.com/ as backend
  
- [ ] Tier maker
  - [ ] Choose from different sets e.g. weapons, stages, specials etc.
  - [ ] No watermark
  - [ ] Edit tier colors
  - [ ] Normal tier list or one with x & y axis and 4 sections
  - [ ] Export as png

- [ ] Links
  - Probably will be more selective what gets put here. Probably won't just add everything that people tell me but instead select the most useful resources.
  
- [ ] VoDs page
- Search VoDs based on player, weapon, stage, mode, tournament etc. For example you will be able to find best players of Carbon Roller on Mako Zones and study those.

- [ ] Game analyzer
- Upload any private battles. Can connect private battles to tournaments.
- Dashboard of sorts that lets you filter down those games and see stats about them. For example you might discover that on this TC map you are having a lot of problems clearing this checkpoint.
- For example you could set a "focus" with your team for certain maps + players.
- Leave notes or drawings per map.
- Compare comps to see what works the best for any map. Also see what comps other players win with.
- Compare stats between the focused players.

- [ ] Spectator mode analyzer investigation
- Input: spectator mode footage. Output: timeline of events (when special was used, which player went where, who died and by who and where etc. etc. etc.)

- [ ] Gear analyzer investigator
  - [ ] Tool where you can tell which kind of build you want and it looks if you can make from your existing abilities. Gives you options where you can match 2 existing gear and 1 new one you'd have to make one.
  - [ ] Upload gear from save data

**Comment by curtgrimes** [comment]
@Sendouc  Are you accepting PRs for dragging abilities into specific slots? If so I might be interested in tackling that one. I see #82 was closed as completed but I don't think the current build analyzer page supports dragging from what I can tell. Thanks!

**Comment by Sendouc** [comment]
> @Sendouc  Are you accepting PRs for dragging abilities into specific slots? If so I might be interested in tackling that one. I see #82 was closed as completed but I don't think the current build analyzer page supports dragging from what I can tell. Thanks!

Go for it!

**Comment by Sendouc** [comment]
Let's think of some other way to track roadmap 🤔
