### ISSUE TITLE
Splatoon 3 build analyzer

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#913]
## After launch
- [ ] Compare builds
- [ ] Effect tables
- [ ] Main weapon white ink (at least Roller missing but check all)
- [ ] Damage table for all (fizzy, sloshing, curling, roller, splatana, torpedo, angle shooter but check all)
- [ ] Show what effect RP has when splatting others
- [ ] More descriptive Bomb Heavy/Light damage (actual values vs. several different bombs)
- [x] Intensify Action (squid surge)
- [ ] Intensify Action (squid roll)
- [ ] https://twitter.com/AnIceStar23/status/1572300351155605506 splatana weight classes correct?
- [x] "think i found a bug; pretty sure 2 subs iss gives an extra shot on range after suction, doesnt correlate to builder though"
- [x] BASE on same line for each card
- [x] Ink Resistance HP per second seems bugged
- [x] same size:

![Image](https://user-images.githubusercontent.com/38327916/191327027-9b1791e5-9fb3-4436-8bc4-85247481cdfc.png)

## Open question
- [ ] shootingRunSpeed missing from json (RSU)
- [ ] Verify "TripleShotSpanFrame" JSDoc is correct
- [x] What are `DamageParam_ReduceStartFrame` and `DamageParam_ReduceEndFrame`. Show?
- [ ] What are `SpeedInkConsumeMax_WeaponRollParam` and `SpeedInkConsumeMin_WeaponRollParam`
- [x] @ts-expect-error for weaponParamsJson
- [x] Squid Beakon QSJ AP up

## Missing JSON defaults

- [ ] Some subs missing SubInkSaveLv or InkConsume
- [ ] Splat Brella missing CanopyHP
- [ ] Splat Brella missing InkConsume_WeaponShelterShotgunParam

## Requests
- [ ] Shots to destroy objects (Crab, Splash Wall, Wave Breaker) etc. with and without OS + TTK
- [ ] Range
- [ ] "Frame data for shooting/moving could be cool to add"

---

## TODO
- [x] Special Power Up
- [x] Bomb Def
- [x] Intensify Action
- [x] Ninja squid
- [x] Respawn Punisher
- [x] Mobile layout
- [x] Nav link
- [x] Card on front page
- [x] BuildAnalyzerPage early return remove
- [x] Make sure main weapon category can't be empty
- [x] Show RP and NS in stat cards
